### ISSUE TITLE
Data format

### ISSUE THREAD

**Issue by Pro-flynn** [Skype-line/FiNet-pytorch#1]
Thanks for your open source!
I want to run your code to understand the paper, Could you release the train data or tell me the format of data directory?

**Comment by Skype-line** [comment]
Hi,

Thanks for your interest. I am sorry that I cannot share the data with you, since I left them in the school server when I finished my bachelor study last year. But I can tell you how I preprocess and store the data: 
1. for human segmentation map, I use [CIHP_PGN](https://github.com/Engineering-Course/CIHP_PGN), put in the folder "image-parse", PS: you may need to combine certain channels to meet the input requirements of our network;
2. for human pose map, I use [tf-pose-estimation](https://github.com/ildoonet/tf-pose-estimation), put in "pose";
3. for other extracted info, I will upload several helper functions, you can use them.
Above all, the data directory looks like this: 
your_path_to_the_dataset/mode(train or test)/+
1) image(original images); 
2) image-parse; 
3) pose; 
4) bbox_coordinate (bounding box info of 4 types of Contextual Garments);
5) type(hat/top/bottom/shoes)_mode(train/test)_mean.npy.

It seems long time ago, so there might be something I missed. If you have any other questions, let me know :)

Kaiyue

**Comment by LiuYuZzz** [comment]
Hi, 
The data set written on the paper is from DeepFashion, but your source code has spider. So which data set is used?

**Comment by Skype-line** [comment]
> Hi,
> The data set written on the paper is from DeepFashion, but your source code has spider. So which data set is used?

Sorry for misleading. I use DeepFashion dataset. The Scrapy source code is used to collect data for other experiments.

**Comment by LiuYuZzz** [comment]
> > Hi,
> > The data set written on the paper is from DeepFashion, but your source code has spider. So which data set is used?
> 
> Sorry for misleading. I use DeepFashion dataset. The Scrapy source code is used to collect data for other experiments.

And could you tell me how to select 13,821 images that contain more than 3 fashion items to conduct your experiments?

**Comment by LiuYuZzz** [comment]
There is another question.
the class definiation from CIHP_PGN is :
0.background
1.Hat
2.Hair
3.Glove
4.Sunglasses
5.UpperClothes
6.Dress
7.Coat
8.Socks
9.Pants
10.Torso-skin
11.Scarf
12.Skirt
13.Face
14.Left-arm
15.Right-arm
16.Left-leg
17.Right-leg
18.Left-shoe
19.Right-shoe.
which seems different with yours...

**Comment by Skype-line** [comment]
> There is another question.
> the class definiation from CIHP_PGN is :
> 0.background
> 1.Hat
> 2.Hair
> 3.Glove
> 4.Sunglasses
> 5.UpperClothes
> 6.Dress
> 7.Coat
> 8.Socks
> 9.Pants
> 10.Torso-skin
> 11.Scarf
> 12.Skirt
> 13.Face
> 14.Left-arm
> 15.Right-arm
> 16.Left-leg
> 17.Right-leg
> 18.Left-shoe
> 19.Right-shoe.
> which seems different with yours...

Yes. As I said above, "you may need to combine certain channels to meet the input requirements of our network".

**Comment by Skype-line** [comment]
> > > Hi,
> > > The data set written on the paper is from DeepFashion, but your source code has spider. So which data set is used?
> > 
> > 
> > Sorry for misleading. I use DeepFashion dataset. The Scrapy source code is used to collect data for other experiments.
> 
> And could you tell me how to select 13,821 images that contain more than 3 fashion items to conduct your experiments?

Manually :(

**Comment by LiuYuZzz** [comment]
> > There is another question.
> > the class definiation from CIHP_PGN is :
> > 0.background
> > 1.Hat
> > 2.Hair
> > 3.Glove
> > 4.Sunglasses
> > 5.UpperClothes
> > 6.Dress
> > 7.Coat
> > 8.Socks
> > 9.Pants
> > 10.Torso-skin
> > 11.Scarf
> > 12.Skirt
> > 13.Face
> > 14.Left-arm
> > 15.Right-arm
> > 16.Left-leg
> > 17.Right-leg
> > 18.Left-shoe
> > 19.Right-shoe.
> > which seems different with yours...
> 
> Yes. As I said above, "you may need to combine certain channels to meet the input requirements of our network".

I got it! Thank you very much!
